name: Trigger auto deployment for container-app-gudq2sfzzpvci

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-gudq2sfzzpvci-AutoDeployTrigger-5693242c-27dc-4ede-a966-97761e3a1bef.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPGUDQ2SFZZPVCI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPGUDQ2SFZZPVCI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPGUDQ2SFZZPVCI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPGUDQ2SFZZPVCI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPGUDQ2SFZZPVCI_REGISTRY_PASSWORD }}
          containerAppName: container-app-gudq2sfzzpvci
          resourceGroup: elliottrepo8b48
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


